/**
 * Created by Administrator on 2018/7/28 0028.
 */
$(document).ready(function(){
    $("#link1").click(function(){
        $('video').attr('src','./video/5b0eb76c647a4.mp4');
    });
});
$(document).ready(function(){
    $("#link2").click(function(){
        $('video').attr('src','./video/5b0eccec7cdfb.mp4');
    });
});
$(document).ready(function(){
    $("#link3").click(function(){
        $('video').attr('src','./video/5b0ecd946c6b9.mp4');
    });
});
$(document).ready(function(){
    $("#link4").click(function(){
        $('video').attr('src','./video/5b0ecde8a5bfa.mp4');
    });
});
$(document).ready(function(){
    $("#link5").click(function(){
        $('video').attr('src','./video/5b0f91cd5d1f3.mp4');
    });
});
$(document).ready(function(){
    $("#link6").click(function(){
        $('video').attr('src','./video/5b0f91675de51.mp4');
    });
});
$(document).ready(function(){
    $("#link7").click(function(){
        $('video').attr('src','./video/5b0f91973ca0b.mp4');
    });
});
$(document).ready(function(){
    $("#link8").click(function(){
        $('video').attr('src','./video/5b0f9125035e5.mp4');
    });
});
$(document).ready(function(){
    $("#link9").click(function(){
        $('video').attr('src','./video/5b08dd31907e3.mp4');
    });
});
$(document).ready(function(){
    $("#link10").click(function(){
        $('video').attr('src','./video/5b10b8d6d5fd0.mp4');
    });
});
$(document).ready(function(){
    $("#link11").click(function(){
        $('video').attr('src','./video/5b10b9afc7320.mp4');
    });
});
$(document).ready(function(){
    $("#link12").click(function(){
        $('video').attr('src','./video/5b10b94ddf769.mp4');
    });
});
$(document).ready(function(){
    $("#link13").click(function(){
        $('video').attr('src','./video/5b10b914b0472.mp4');
    });
});
$(document).ready(function(){
    $("#link14").click(function(){
        $('video').attr('src','./video/5b10b98598b53.mp4');
    });
});
$(document).ready(function(){
    $("#link15").click(function(){
        $('video').attr('src','./video/5b27c35884459.mp4');
    });
});
$(document).ready(function(){
    $("#link16").click(function(){
        $('video').attr('src','./video/5b30df8db0a43.mp4');
    });
});
$(document).ready(function(){
    $("#link17").click(function(){
        $('video').attr('src','./video/5b0427e86f2b0.mp4');
    });
});
$(document).ready(function(){
    $("#link18").click(function(){
        $('video').attr('src','./video/5b0428bc996ff.mp4');
    });
});
$(document).ready(function(){
    $("#link19").click(function(){
        $('video').attr('src','./video/5b04280a39324.mp4');
    });
});
$(document).ready(function(){
    $("#link20").click(function(){
        $('video').attr('src','./video/5b042839cc586.mp4');
    });
});
$(document).ready(function(){
    $("#link21").click(function(){
        $('video').attr('src','./video/5b0427548aa4d.mp4');
    });
});
$(document).ready(function(){
    $("#link22").click(function(){
        $('video').attr('src','./video/5b3633194cb26.mp4');
    });
});



//按钮菜单视频的切换
$(document).ready(function(){
    $("#link111").click(function(){
        $('video').attr('src','./video/5b0eb76c647a4.mp4');
    });
});
$(document).ready(function(){
    $("#link211").click(function(){
        $('video').attr('src','./video/5b0eccec7cdfb.mp4');
    });
});
$(document).ready(function(){
    $("#link31").click(function(){
        $('video').attr('src','./video/5b0ecd946c6b9.mp4');
    });
});
$(document).ready(function(){
    $("#link41").click(function(){
        $('video').attr('src','./video/5b0ecde8a5bfa.mp4');
    });
});
$(document).ready(function(){
    $("#link51").click(function(){
        $('video').attr('src','./video/5b0f91cd5d1f3.mp4');
    });
});
$(document).ready(function(){
    $("#link61").click(function(){
        $('video').attr('src','./video/5b0f91675de51.mp4');
    });
});
$(document).ready(function(){
    $("#link71").click(function(){
        $('video').attr('src','./video/5b0f91973ca0b.mp4');
    });
});
$(document).ready(function(){
    $("#link81").click(function(){
        $('video').attr('src','./video/5b0f9125035e5.mp4');
    });
});
$(document).ready(function(){
    $("#link91").click(function(){
        $('video').attr('src','./video/5b08dd31907e3.mp4');
    });
});
$(document).ready(function(){
    $("#link101").click(function(){
        $('video').attr('src','./video/5b10b8d6d5fd0.mp4');
    });
});
$(document).ready(function(){
    $("#link1111").click(function(){
        $('video').attr('src','./video/5b10b9afc7320.mp4');
    });
});
$(document).ready(function(){
    $("#link121").click(function(){
        $('video').attr('src','./video/5b10b94ddf769.mp4');
    });
});
$(document).ready(function(){
    $("#link131").click(function(){
        $('video').attr('src','./video/5b10b914b0472.mp4');
    });
});
$(document).ready(function(){
    $("#link141").click(function(){
        $('video').attr('src','./video/5b10b98598b53.mp4');
    });
});
$(document).ready(function(){
    $("#link151").click(function(){
        $('video').attr('src','./video/5b27c35884459.mp4');
    });
});
$(document).ready(function(){
    $("#link161").click(function(){
        $('video').attr('src','./video/5b30df8db0a43.mp4');
    });
});
$(document).ready(function(){
    $("#link171").click(function(){
        $('video').attr('src','./video/5b0427e86f2b0.mp4');
    });
});
$(document).ready(function(){
    $("#link181").click(function(){
        $('video').attr('src','./video/5b0428bc996ff.mp4');
    });
});
$(document).ready(function(){
    $("#link19").click(function(){
        $('video').attr('src','./video/5b04280a39324.mp4');
    });
});
$(document).ready(function(){
    $("#link201").click(function(){
        $('video').attr('src','./video/5b042839cc586.mp4');
    });
});
$(document).ready(function(){
    $("#link2111").click(function(){
        $('video').attr('src','./video/5b0427548aa4d.mp4');
    });
});
$(document).ready(function(){
    $("#link221").click(function(){
        $('video').attr('src','./video/5b3633194cb26.mp4');
    });
});



/*
if ((navigator.userAgent.indexOf('MSIE') >= 0)
    && (navigator.userAgent.indexOf('Opera') < 0)){
    $('a7').attr('margin-bottom','97px');
}else {
    $('a7').attr('margin-bottom','20px');
}*/
